### PR TITLE
fix(ARCH-631): explicit use sass-data

### PR DESCRIPTION
**Pull request by jmfrancois**
**What is the problem this PR is trying to solve?**

our current tools add sass-data so scss file rely on defined variables, but developer write variables without include them.
This block us to use tools like create-react-app

**What is the chosen solution to this problem?**

* create script to do that: https://gist.github.com/jmfrancois/402c32c22fba98f1e35599f1e0dab2c2
* explicitly add use of the sass data

to test it, I have applied it in /lib folder of create-react-app and did the job to fix all build errors.

image

**Please check if the PR fulfills these requirements**

- [ ] The PR have used `yarn changeset` to a request a release from the CI if wanted.
- [ ] The PR commit message follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md)
- [ ] Tests for the changes have been added (for bug fixes / features) And [non reg](./screenshots.md) done before need review
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] Related design / discussions / pages (not in jira), if any, are all linked or available in the PR

**[ ] This PR introduces a breaking change**

### CODE REVIEW

**Review by Benrajalu — COMMENTED** [review]
This might be a pain but hear me out while you're scripting stuff: 
 
 `@use '~@talend/bootstrap-theme/src/theme/guidelines' as bootstrap;` instead.
 
And prefix all usages then with `bootstrap.` (that's clearly the painful part)
 
When you move to remove bootstrap, you'll be able to figure out exactly what remains to be cleaned up. And devs having to write `bootstrap.` should make it obvious there's something wrong :D

**Comment by jmfrancois** [comment]
I am agree that could be nice to track down usage. But yeah not painful but have to spend time for that. Let's see that as a bonus, it could be done later.

**Comment by Gbacc** [comment]
The idea is to have this import on all scss files in TUI ? 
So it could happen we add a new file and forget about it. How could we prevent that except during reviews ?

**Review by smouillour — APPROVED** [review]

**Review by Benrajalu — APPROVED** [review]

**Review by tlnd-mhuchet — APPROVED** [review]

**Comment by tlnd-mhuchet** [comment]
> The idea is to have this import on all scss files in TUI ? So it could happen we add a new file and forget about it. How could we prevent that except during reviews ?

Adding a custom (or if one exist already) stylelint rule ? But linter are not really taken seriously in projects 😅

**Pull request merged**
