### PR TITLE
fix(forms): manage a list of value with coma separator

### PR DESCRIPTION
**Pull request by jlame**
**Please check if the PR fulfills these requirements**

- [x] The commit(s) message(s) follows our
  [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md#commit-message-format)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**
Before we were just using the first attribute of the array as a value, now we send the whole array.

**Does this PR introduce a breaking change?**

- [x] Yes
- [ ] No

If this PR contains a breaking change, please describe the impact and migration
path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by jmfrancois** [comment]
:octocat: [Demo is available here](http://413.talend.surge.sh)

**Comment by jmfrancois** [comment]
:octocat: [Demo is available here](http://413.talend.surge.sh)

**Comment by jmfrancois** [comment]
:octocat: [Demo is available here](http://413.talend.surge.sh)

**Comment by jlame** [comment]
In fact today, there's no UX guide or specific way of managing multiple values on one line. So while waiting for the moment we implement it, it was decided that this would be the current behaviour. It could be possible to remove all of that logic and let the host widget manage this but that would make it impossible to enter multiple value in the "disconnected" mode.

**Comment by jmfrancois** [comment]
:octocat: [Demo is available here](http://413.talend.surge.sh)

**Comment by jmfrancois** [comment]
:octocat: [Demo is available here](http://413.talend.surge.sh)

**Pull request merged**
