### PR TITLE
feat(components/TreeView): add customization options and counter

### PR DESCRIPTION
**Pull request by sdwvit**
**Please check if the PR fulfills these requirements**

- [x] The commit(s) message(s) follows our
  [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md#commit-message-format)
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What is the new behavior?**
added custom actions
breaking: removed removeCallback in favor of custom actions
added counter
added handle for custom item icons

and many other good changes

**Does this PR introduce a breaking change?**

- [x] Yes
- [ ] No

If this PR contains a breaking change, please describe the impact and migration
path for existing applications: ...

breaking: removed removeCallback in favor of custom actions

**Other information**:

### CODE REVIEW

**Comment by sdwvit** [comment]
screen shot 2017-03-06 at 21 44 37

**Comment by jmfrancois** [comment]
:octocat: [Demo is available here](http://240.talend.surge.sh)

**Comment by jmfrancois** [comment]
:octocat: [Demo is available here](http://240.talend.surge.sh)

**Comment by jmfrancois** [comment]
:octocat: [Demo is available here](http://240.talend.surge.sh)

**Comment by jmfrancois** [comment]
:octocat: [Demo is available here](http://240.talend.surge.sh)

**Comment by jmfrancois** [comment]
:octocat: [Demo is available here](http://240.talend.surge.sh)

**Comment by sdwvit** [comment]
@jmfrancois https://github.com/Talend/ui/pull/260

**Comment by jmfrancois** [comment]
:octocat: [Demo is available here](http://240.talend.surge.sh)

**Comment by jmfrancois** [comment]
:octocat: [Demo is available here](http://240.talend.surge.sh)

**Comment by jmfrancois** [comment]
:octocat: [Demo is available here](http://240.talend.surge.sh)

**Comment by jmfrancois** [comment]
:octocat: [Demo is available here](http://240.talend.surge.sh)

**Comment by jmfrancois** [comment]
:octocat: [Demo is available here](http://240.talend.surge.sh)

**Pull request merged**
