### PR TITLE
feat(icons): classify, wrench, grouping, merge

### PR DESCRIPTION
**Pull request by mhuet**
**What is the problem this PR is trying to solve?**
TDS needs icons for the campaign type dropdown. 
https://jira.talendforge.org/browse/TUX-885

**What is the chosen solution to this problem?**
Icons has been created.

**Please check if the PR fulfills these requirements**

* [ ] The PR commit message follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md)
* [ ] Tests for the changes have been added (for bug fixes / features) And [non reg](./screenshots.md) done before need review
* [ ] Docs have been added / updated (for bug fixes / features)
* [ ] Related design / discussions / pages (not in jira), if any, are all linked or available in the PR

**[ ] This PR introduces a breaking change**

### CODE REVIEW

**Comment by mhuet** [comment]
@sgendre those icons are going to be used by other apps — it has been created at first for TDS.

**Comment by sgendre** [comment]
so others apps will load the appropriate bundle when they need it, and should not load it without noticing it monthes before they actually need it

otherwise lets put everything in core

**Comment by jsomsanith-tlnd** [comment]
@sgendre as suggested on Slack, can you give some suggestions in the folder hierarchie / bundle split please. You expose a problem, instead of stepping back, take the same time to propose the right categories please.

**Comment by jsomsanith-tlnd** [comment]
As Monia said, the icons don't seem to be TDS specific. It's just that it's introduced now because they need them now, but again, not specific.
Open to generic categories suggestions, not app specific

**Pull request merged**
