### PR TITLE
chore(lint): Fixes a lot of linting issues

### PR DESCRIPTION
**Pull request by talend-glorieux**
**Please check if the PR fulfills these requirements**

- [x] The commit(s) message(s) follows our
  [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md#commit-message-format)
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What is the current behavior?** (You can also link to an open issue here)

There are quite a bit of lint issues.

**What is the new behavior?**

Most lint issues are fixed.

### CODE REVIEW

**Comment by talend-glorieux** [comment]
⚠️ Dont't merge yet. I will take a look at travis setup.

**Comment by jmfrancois** [comment]
:octocat: [Demo is available here](http://106.talend.surge.sh)

**Comment by jmfrancois** [comment]
:octocat: [Demo is available here](http://106.talend.surge.sh)

**Comment by jmfrancois** [comment]
:octocat: [Demo is available here](http://106.talend.surge.sh)

**Comment by jmfrancois** [comment]
:octocat: [Demo is available here](http://106.talend.surge.sh)

**Pull request merged**
