### PR TITLE
chore(component): use Icon & Provider from design-system

### PR DESCRIPTION
**Pull request by jmfrancois**
**What is the problem this PR is trying to solve?**

Icon and IconsProvider are in Talend ui but we need them in the design system as core components.
So to avoid circular dependencies we have moved them to DS.

**What is the chosen solution to this problem?**

Replace Icon and IconsProvider by the one in DS.
Note: we have removed 

* onclick on the Icon component
* font awesome support (never really supported)

**Please check if the PR fulfills these requirements**

* [x] The PR commit message follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md)
* [ ] Tests for the changes have been added (for bug fixes / features) And [non reg](./screenshots.md) done before need review
* [ ] Docs have been added / updated (for bug fixes / features)
* [ ] Related design / discussions / pages (not in jira), if any, are all linked or available in the PR

**[ ] This PR introduces a breaking change**

### CODE REVIEW

**Review by frassinier — APPROVED** [review]

**Comment by frassinier** [comment]
There is a color issue with `Status` and `InlineMessage` at least

**Comment by frassinier** [comment]
I would be in favor to keep Icon stories WDYT

**Comment by jmfrancois** [comment]
I prefere move them to DS

**Comment by jmfrancois** [comment]
So the issue on Status and InlineMessage is fixed !

**Review by ncomont — APPROVED** [review]

**Comment by frassinier** [comment]
We may need to use this https://github.com/styled-components/jest-styled-components

**Pull request merged**
