### PR TITLE
chore(forms): Adds errorSchema story

### PR DESCRIPTION
**Pull request by talend-glorieux**
**Please check if the PR fulfills these requirements**

- [x] The commit(s) message(s) follows our
  [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md#commit-message-format)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What is the current behavior?** (You can also link to an open issue here)

The forms storybook doesn't have any errorSchema usage example.

**What is the new behavior?**

The forms storybook has a errorSchema usage example.

### CODE REVIEW

**Comment by jmfrancois** [comment]
:octocat: [Demo is available here](http://211.talend.surge.sh)

**Comment by jmfrancois** [comment]
:octocat: [Demo is available here](http://211.talend.surge.sh)

**Comment by jmfrancois** [comment]
:octocat: [Demo is available here](http://211.talend.surge.sh)

**Comment by jmfrancois** [comment]
:octocat: [Demo is available here](http://211.talend.surge.sh)

**Comment by jsomsanith** [comment]
close for inactivity

**Pull request closed without merging**
