### PR TITLE
feat(forms): remove onblur in order to be able to scroll by dragging

### PR DESCRIPTION
**Pull request by charlesnguyen**
**Please check if the PR fulfills these requirements**

- [x] The commit(s) message(s) follows our
  [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md#commit-message-format)
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What is the current behavior?** (You can also link to an open issue here)
When the dropdown menu of datalistWidget has vertical scroll, we can not scroll by dragging the scroll button, because it fires onblur of the input, hence the dropdown menu disappears
image

**What is the new behavior?**
Onblur of the input is not fired when scrolling by dragging the scroll button, the dropdown menu is closed only when selecting an dropdown menu item or reseting the input.
we have the same behaviour as the typeahead

**Does this PR introduce a breaking change?**

- [ ] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration
path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by jmfrancois** [comment]
:octocat: [Demo is available here](http://284.talend.surge.sh)

**Comment by jmfrancois** [comment]
:octocat: [Demo is available here](http://284.talend.surge.sh)

**Comment by jmfrancois** [comment]
:octocat: [Demo is available here](http://284.talend.surge.sh)

**Comment by talend-glorieux** [comment]
Could you please add an example?
It'll make it easier to understand what you're trying to accomplish.

**Comment by frassinier** [comment]
This could be closed I guess?

**Pull request closed without merging**
