### PR TITLE
fix(Generator): add fetch polyfill

### LINKED ISSUE #175: react-cmf generator doesn't work on first run in safari

### PR DESCRIPTION
**Pull request by jsomsanith**
**Please check if the PR fulfills these requirements**

- [x] The commit(s) message(s) follows our
  [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md#commit-message-format)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What is the current behavior?** (You can also link to an open issue here)
No fetch polyfill, the `fetch`results in error in Safari.

**What is the new behavior?**
Added a fetch polyfill

This fix #175

**Does this PR introduce a breaking change?**

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by jmfrancois** [comment]
:octocat: [Demo is available here](http://181.talend.surge.sh)

**Comment by jmfrancois** [comment]
:octocat: [Demo is available here](http://181.talend.surge.sh)

**Comment by frassinier** [comment]
:+1: for @talend-sromain's comment

**Comment by jmfrancois** [comment]
:octocat: [Demo is available here](http://181.talend.surge.sh)

**Comment by jmfrancois** [comment]
:octocat: [Demo is available here](http://181.talend.surge.sh)

**Pull request merged**
