### PR TITLE
fix(components/SidePanel): fix toggle icon for SidePanel

### PR DESCRIPTION
**Pull request by mtikhinskaya**
**Please check if the PR fulfills these requirements**

- [x] The commit(s) message(s) follows our
  [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md#commit-message-format)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What is the current behavior?** (You can also link to an open issue here)

image

**What is the new behavior?**

image

**Does this PR introduce a breaking change?**

- [ ] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration
path for existing applications: ...

**Other information**:
Link to Frontify: http://guidelines.talend.com/document/92132#/navigation-layout/side-panel

### CODE REVIEW

**Comment by jmfrancois** [comment]
:octocat: [Demo is available here](http://310.talend.surge.sh)

**Comment by jmfrancois** [comment]
:octocat: [Demo is available here](http://310.talend.surge.sh)

**Comment by jmfrancois** [comment]
:octocat: [Demo is available here](http://310.talend.surge.sh)

**Comment by mtikhinskaya** [comment]
When we use border it's impossible to align it. So we will have icon and border with different alignments.
Why it's better to use border?

**Comment by jare-talend** [comment]
In my opinion, The use "|" has no semantic sense. @frassinier what do you thing about it?

**Comment by mtikhinskaya** [comment]
It was agreed to use this separator for HeaderBar. Please check: https://github.com/Talend/ui/blob/master/packages/components/src/HeaderBar/HeaderBar.scss#L27

For me content is a better choice because of the color problems with the border.

**Comment by jmfrancois** [comment]
:octocat: [Demo is available here](http://310.talend.surge.sh)

**Comment by jmfrancois** [comment]
:octocat: [Demo is available here](http://310.talend.surge.sh)

**Pull request merged**
