### PR TITLE
fix(theme): remove the clear button on all input on ie/edge

### PR DESCRIPTION
**Pull request by jare-talend**
**Please check if the PR fulfills these requirements**

- [X] The commit(s) message(s) follows our
  [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md#commit-message-format)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What is the current behavior?** (You can also link to an open issue here)
IE/Edge add one clear button when the input has focused and not empty. The behavor is specific to IE10+/Edge and we doesn't have on the other browsers.

ms-clear

**What is the new behavior?**
ms-clear-with

**Does this PR introduce a breaking change?**

- [ ] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration
path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by jmfrancois** [comment]
:octocat: [Demo is available here](http://242.talend.surge.sh)

**Comment by jare-talend** [comment]
Except the input can be use without form (ex: list component http://talend.surge.sh/components/?selectedKind=List&selectedStory=Table%20%28default%29&full=0&down=1&left=1&panelRight=0&downPanel=kadirahq%2Fstorybook-addon-actions%2Factions-panel)

**Comment by jmfrancois** [comment]
no way it's accessibility ;) you wanna kill @frassinier

**Comment by frassinier** [comment]
In fact, `<input>` should be **everytime** inside a `<form />` .

WAT

But I agree with your selector. :ok_hand:  
Indeed, like for `<td>`, since they exist inside `<table>` we cannot write `table tbody tr td { ... }`, we can write `td { ... }` directly...

**Comment by acateland** [comment]
on my side im not sure we should circumvent a default browser behavior like this one. My guess is that for IE user (yes they exists) it could be disturbing not to have acces to this ux element. Have you checked with the UX team ?

**Comment by jare-talend** [comment]
I see with maxime, we remove this behavior on IE.

**Comment by jmfrancois** [comment]
:octocat: [Demo is available here](http://242.talend.surge.sh)

**Comment by jmfrancois** [comment]
:octocat: [Demo is available here](http://242.talend.surge.sh)

**Comment by jmfrancois** [comment]
:octocat: [Demo is available here](http://242.talend.surge.sh)

**Comment by jmfrancois** [comment]
:octocat: [Demo is available here](http://242.talend.surge.sh)

**Comment by jmfrancois** [comment]
:octocat: [Demo is available here](http://242.talend.surge.sh)

**Pull request merged**
