### PR TITLE
patch(forms): datalist

### PR DESCRIPTION
**Pull request by frassinier**
**Please check if the PR fulfills these requirements**

- [x] The commit(s) message(s) follows our
  [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md#commit-message-format)
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What is the current behavior?** (You can also link to an open issue here)
If blur is triggered with unknown value, datalist will be reset to blank

**What is the new behavior?**
If blur is triggered with unknown value, datalist will be reset to the last known valid value

In addition, datalist widget style uses Bootstrap theme variables instead

**Does this PR introduce a breaking change?**

- [ ] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration
path for existing applications: ...

**Other information**:
That PR will be merged to #134

### CODE REVIEW

**Comment by jmfrancois** [comment]
:octocat: [Demo is available here](http://188.talend.surge.sh)

**Comment by jmfrancois** [comment]
:octocat: [Demo is available here](http://188.talend.surge.sh)

**Comment by talend-glorieux** [comment]
Is this a change on something else than master?

**Comment by jmfrancois** [comment]
:octocat: [Demo is available here](http://188.talend.surge.sh)

**Pull request merged**
