### PR TITLE
fix(Components): list filter input/button alignment

### PR DESCRIPTION
**Pull request by jsomsanith**
**Please check if the PR fulfills these requirements**

- [x] The commit(s) message(s) follows our
  [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md#commit-message-format)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What is the current behavior?** (You can also link to an open issue here)
capture d ecran de 2017-02-15 11-47-35

The filter input/button alignment i snot correct after a change in theme.

**What is the new behavior?**
To enforce the alignment (not depending on the theme), we now explicitly request a display in this group.

**Does this PR introduce a breaking change?**

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by jmfrancois** [comment]
:octocat: [Demo is available here](http://160.talend.surge.sh)

**Comment by jmfrancois** [comment]
:octocat: [Demo is available here](http://160.talend.surge.sh)

**Comment by jmfrancois** [comment]
:octocat: [Demo is available here](http://160.talend.surge.sh)

**Comment by jsomsanith** [comment]
fixed by @frassinier, this is not needed anymore

**Pull request closed without merging**
