### PR TITLE
fix(IconsProvider): empty container before append icon

### PR DESCRIPTION
**Pull request by jmfrancois**
**What is the problem this PR is trying to solve?**

Current if Icon props change the icon is appended so we have a second icon

**What is the chosen solution to this problem?**

* add story for that
* fix the bug

Screen-Recording-2020-11-19-at-1

**Please check if the PR fulfills these requirements**

* [x] The PR commit message follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md)
* [ ] Tests for the changes have been added (for bug fixes / features) And [non reg](./screenshots.md) done before need review
* [x] Docs have been added / updated (for bug fixes / features)
* [ ] Related design / discussions / pages (not in jira), if any, are all linked or available in the PR

**[ ] This PR introduces a breaking change**

### CODE REVIEW

**Review by romainseb — APPROVED** [review]

**Comment by lmaillet** [comment]
Icons are not loaded in storybook.
GET http://3085.talend.surge.sh/all.svg 404 (Not Found)

**Review by jsomsanith-tlnd — APPROVED** [review]

**Comment by jsomsanith-tlnd** [comment]
> Icons are not loaded in storybook.
> GET http://3085.talend.surge.sh/all.svg 404 (Not Found)

Are you looking for http://3085.talend.surge.sh/icons/dist/svg-bundle/all.svg ?
I don't understand your point, can you give us more details of what you want to do ?

**Comment by lmaillet** [comment]
Just trying to see the update story from @jmfrancois.
http://3085.talend.surge.sh/components/?path=/story/messaging-communication-icon--default-use-svg

image

**Comment by jsomsanith-tlnd** [comment]
Oh good catch, I haven't tested on the published storybook

**Review by sgangnant — APPROVED** [review]

**Review by lmaillet — APPROVED** [review]

**Pull request merged**
