### PR TITLE
fix(cmf): http middleware doesn't handle 204 HTTP status with empty body

### PR DESCRIPTION
**Pull request by jlame**
**Please check if the PR fulfills these requirements**
- [x] The commit(s) message(s) follows our
  [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md#commit-message-format)
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What is the current behavior?** (You can also link to an open issue here)
When receiving http response code 204 with no content in response, an exception was raised.

**What is the new behavior?**
When receiving http response code 204 with no content in response, no error is raised.

**Other information**:
There might be another solution to solve this issue, but this one seems to be the easiest. As for the moment, most of our app only accept json as a return. Any thought ?

(cherry picked from commit 452e6e6)

### CODE REVIEW

**Comment by talend-glorieux** [comment]
I'll resolve the merge conflicts and take another look at the tests.

**Comment by talend-glorieux** [comment]
Good to merge one tests are green 👍

**Comment by jmfrancois** [comment]
:octocat: [Demo is available here](http://197.talend.surge.sh)

**Comment by jmfrancois** [comment]
:octocat: [Demo is available here](http://197.talend.surge.sh)

**Pull request merged**
