### PR TITLE
fix(CMF): remove extra map on provider children

### PR DESCRIPTION
**Pull request by jsomsanith**
**Please check if the PR fulfills these requirements**

- [x] The commit(s) message(s) follows our
  [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md#commit-message-format)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What is the current behavior?** (You can also link to an open issue here)
The CMF `RegistryProvider` map the children to insert a `this.onClick` that is undefined.

**What is the new behavior?**
Removed that

**Does this PR introduce a breaking change?**

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by jmfrancois** [comment]
:octocat: [Demo is available here](http://163.talend.surge.sh)

**Comment by jmfrancois** [comment]
:octocat: [Demo is available here](http://163.talend.surge.sh)

**Comment by jsomsanith** [comment]
Sorry I don't really understand, the previous code was mapping the all the children, but was returning only the first child.
I just changed the code that was not necessary to do almost the same, but instead of dropping the other children, we throw because it may not be what the developer want. Isn't that correct ?

Can you explain a little more `You may use CMF with multiple children (in the case of embeded app)` ?

**Comment by jmfrancois** [comment]
:octocat: [Demo is available here](http://163.talend.surge.sh)

**Comment by jmfrancois** [comment]
:octocat: [Demo is available here](http://163.talend.surge.sh)

**Comment by jmfrancois** [comment]
:octocat: [Demo is available here](http://163.talend.surge.sh)

**Comment by jmfrancois** [comment]
:octocat: [Demo is available here](http://163.talend.surge.sh)

**Comment by jmfrancois** [comment]
:octocat: [Demo is available here](http://163.talend.surge.sh)

**Comment by jmfrancois** [comment]
:octocat: [Demo is available here](http://163.talend.surge.sh)

**Comment by jmfrancois** [comment]
:octocat: [Demo is available here](http://163.talend.surge.sh)

**Pull request merged**
