### PR TITLE
feat(icons): add a stop icon

### PR DESCRIPTION
**Pull request by acateland**
**Please check if the PR fulfills these requirements**

- [x] The commit(s) message(s) follows our
  [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md#commit-message-format)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?**

- [ ] Yes
- [x] No

**Other information**:

### CODE REVIEW

**Comment by jmfrancois** [comment]
:octocat: [Demo is available here](http://145.talend.surge.sh)

**Comment by jmfrancois** [comment]
:octocat: [Demo is available here](http://145.talend.surge.sh)

**Comment by talend-glorieux** [comment]
Is this ready for review ?

**Comment by jmfrancois** [comment]
:octocat: [Demo is available here](http://145.talend.surge.sh)

**Comment by jmfrancois** [comment]
:octocat: [Demo is available here](http://145.talend.surge.sh)

**Pull request merged**
