### PR TITLE
feat(components/drawer): style

### PR DESCRIPTION
**Pull request by frassinier**
**What is the problem this PR is trying to solve?**
Drawers style is not up to date

**What is the chosen solution to this problem?**
Implement guidelines

Will be a prerequisite of :
* https://github.com/Talend/ui-dataset/pull/145
* https://github.com/Talend/ui-data-quality-semantic-ee/pull/8

**Please check if the PR fulfills these requirements**

* [x] The PR commit message follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md)
* [ ] Tests for the changes have been added (for bug fixes / features) And [non reg](./screenshots.md) done before need review
* [ ] Docs have been added / updated (for bug fixes / features)
* [x] Related design / discussions / pages (not in jira), if any, are all linked or available in the PR

http://guidelines.talend.com/document/92132#/navigation-layout/drawer-v2

**[ ] This PR introduces a breaking change**

### CODE REVIEW

**Comment by ncomont** [comment]
image
margin between tabs bar and content is no longer valid

**Comment by ncomont** [comment]
image
when stacked, the background drawer does not have the gray overlay

**Comment by ncomont** [comment]
image
I can't see any guideline showing the close button in the title. I guess it shouldn't be there, right ?

**Comment by ncomont** [comment]
image
When the drawer title is too long, ellipsis should be there (that's what the story says. anyway, the line height seems a bit thin)

**Comment by ncomont** [comment]
image
strange shadows on forms footers

**Comment by ncomont** [comment]
image
... but no shadows on the "drawer stacked" form story. btw, sometimes the guidelines shows a shadow, sometimes no. is there any rule on that ?

**Comment by ncomont** [comment]
image

this PR seems to affect every sticky footer, in drawer, but also in modals. Master on the left (sticky submit button), this branch on the right (you've to scroll to see it).

**Comment by frassinier** [comment]
> image
> 
> I can't see any guideline showing the close button in the title. I guess it shouldn't be there, right ?

It can be here if and only if there is no cancel button at all

**Comment by frassinier** [comment]
> image
> 
> strange shadows on forms footers

It comes from guidelines

**Comment by frassinier** [comment]
> image
> 
> ... but no shadows on the "drawer stacked" form story. btw, sometimes the guidelines shows a shadow, sometimes no. is there any rule on that ?

Actually, there is a shadow if the drawer is not full-page (aka stacked)

**Pull request merged**
