### PR TITLE
fix(components): list with table cell behavior more precise

### PR DESCRIPTION
**Pull request by frassinier**
**Please check if the PR fulfills these requirements**

- [x] The commit(s) message(s) follows our
  [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md#commit-message-format)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What is the current behavior?** (You can also link to an open issue here)
Others columns than title one have `.actions` which their width decrease

**What is the new behavior?**
Just actions next to item title vanish.  

**Does this PR introduce a breaking change?**

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by jmfrancois** [comment]
:octocat: [Demo is available here](http://111.talend.surge.sh)

**Comment by charlesnguyen** [comment]
We have a problem onIE11, the columns move on hover.

**Comment by jmfrancois** [comment]
:octocat: [Demo is available here](http://111.talend.surge.sh)

**Comment by jmfrancois** [comment]
:octocat: [Demo is available here](http://111.talend.surge.sh)

**Comment by frassinier** [comment]
@charlesnguyen Could you double check now please?

**Comment by jmfrancois** [comment]
:octocat: [Demo is available here](http://111.talend.surge.sh)

**Comment by jmfrancois** [comment]
:octocat: [Demo is available here](http://111.talend.surge.sh)

**Comment by jmfrancois** [comment]
:octocat: [Demo is available here](http://111.talend.surge.sh)

**Comment by jmfrancois** [comment]
:octocat: [Demo is available here](http://111.talend.surge.sh)

**Comment by jmfrancois** [comment]
:octocat: [Demo is available here](http://111.talend.surge.sh)

**Comment by jmfrancois** [comment]
:octocat: [Demo is available here](http://111.talend.surge.sh)

**Pull request merged**
