### PR TITLE
chore(components): Code Style & Lint refactoring

### PR DESCRIPTION
**Pull request by talend-glorieux**
**Please check if the PR fulfills these requirements**

- [x] The commit(s) message(s) follows our
  [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md#commit-message-format)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What is the current behavior?** (You can also link to an open issue here)

Some lint errors and code style issues.

**What is the new behavior?**

* Fixes lint issues
* Fixes code style

### CODE REVIEW

**Comment by talend-glorieux** [comment]
Now let's get those tests to pass :)

**Comment by jmfrancois** [comment]
:octocat: [Demo is available here](http://137.talend.surge.sh)

**Comment by jmfrancois** [comment]
:octocat: [Demo is available here](http://137.talend.surge.sh)

**Comment by jmfrancois** [comment]
:octocat: [Demo is available here](http://137.talend.surge.sh)

**Comment by jmfrancois** [comment]
:octocat: [Demo is available here](http://137.talend.surge.sh)

**Pull request merged**
